# Generated by Django 5.1.2 on 2024-10-17 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_assessment', '0002_customuser_delete_userassessment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
